### ISSUE TITLE
devel+classic-post-refactor branch does not sync to latest block 

### ISSUE THREAD

**Issue by DRIgnazGortngschirl** [ETCCooperative/erigon#67]
System information

Erigon version: ./erigon --version

OS & Version: Windows/Linux/OSX

OS: Debian GNU/Linux 11 (bullseye) x86_64
Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-7.1)
Kernel: 5.10.0-19-amd64
Uptime: 6 days, 5 hours, 3 mins
Packages: 563 (dpkg)
hell: bash 5.1.4
Resolution: 1280x800
Terminal: /dev/pts/1
CPU: AMD EPYC 7282 (8) @ 2.794GHz
GPU: 00:02.0 Vendor 1234 Device 1111
Memory: 28239MiB / 32112MiB

Erigon Command (with flags/config):

erigon --chain=classic --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=[https://explorer-expedition.etc-network.info,https://chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info](https://explorer-expedition.etc-network.info,https//chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info) --http.api=eth,debug,net,admin --rpc.batch.limit 1500 --maxpeers=16

Chain/Network: mainnet
Expected behavior

Syncs to latest block 

Actual behavior

stops at random blocks 
```
erigon_1       | [INFO] [07-04|17:46:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:46:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:46:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:47:14.315] [p2p] GoodPeers                          eth68=33 eth66=15 eth67=18
erigon_1       | [INFO] [07-04|17:47:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:47:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:47:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:47:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:48:14.342] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.7GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:48:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:48:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:48:54.361] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:49:14.315] [p2p] GoodPeers                          eth68=33 eth67=18 eth66=15
erigon_1       | [INFO] [07-04|17:49:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:49:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:49:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:49:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [WARN] [07-04|17:50:06.546] Served                                   conn=172.18.0.4:37024 method=admin_peers reqid=1 t=48.799µs err="the method admin_peers does not exist/is not available"
erigon_1       | [INFO] [07-04|17:50:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.1GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:50:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:50:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:50:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:51:14.315] [p2p] GoodPeers                          eth68=33 eth66=15 eth67=18
erigon_1       | [INFO] [07-04|17:51:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:51:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:51:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:51:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:52:14.342] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.1GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:52:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:52:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:52:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:53:14.315] [p2p] GoodPeers                          eth67=18 eth68=33 eth66=15
erigon_1       | [INFO] [07-04|17:53:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:53:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:53:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:53:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:54:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.1GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:54:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:54:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:54:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:55:14.329] [p2p] GoodPeers                          eth68=33 eth66=15 eth67=18
erigon_1       | [INFO] [07-04|17:55:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:55:14.361] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:55:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:55:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:56:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.1GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:56:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:56:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:56:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:57:14.316] [p2p] GoodPeers                          eth68=33 eth67=18 eth66=15
erigon_1       | [INFO] [07-04|17:57:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:57:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:57:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:57:54.361] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:58:14.342] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.0GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:58:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:58:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:58:54.361] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:59:14.316] [p2p] GoodPeers                          eth68=33 eth67=18 eth66=15
erigon_1       | [INFO] [07-04|17:59:14.343] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.9GB sys=3.7GB
erigon_1       | [INFO] [07-04|17:59:14.363] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:59:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|17:59:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [WARN] [07-04|18:00:05.317] Served                                   conn=172.18.0.4:59080 method=admin_peers reqid=1 t=27.851µs err="the method admin_peers does not exist/is not available"
erigon_1       | [INFO] [07-04|18:00:14.342] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=2.0GB sys=3.7GB
erigon_1       | [INFO] [07-04|18:00:14.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|18:00:34.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|18:00:54.362] [2/15 Headers] No block headers to write in this log period block number=1938042
erigon_1       | [INFO] [07-04|18:01:14.316] [p2p] GoodPeers                          eth68=33 eth66=15 eth67=18
erigon_1       | [INFO] [07-04|18:01:14.342] [txpool] stat                            pending=0 baseFee=0 queued=25 alloc=1.8GB sys=3.7GB
erigon_1       | [INFO] [07-04|18:01:14.361] [2/15 Headers] No block headers to write in this log period block number=1938042
```
Steps to reproduce the behavior

use devel+classic-post-refactor branch and start to sync

**Comment by meowsbits** [comment]
`number=1938042` is suspiciously close to 1920000, the DAO fork block. Will have to investigate.

**Comment by DRIgnazGortngschirl** [comment]
@meowsbits I am here if some testing is needed.

**Comment by meowsbits** [comment]
```
[TRACE] [08-21|10:50:15.797] [downloader] Link queue                  size=303643
[TRACE] [08-21|10:50:15.797] [downloader] Link queue                  size=303643
[TRACE] [08-21|10:50:15.797] [downloader] Link queue                  size=303643
[TRACE] [08-21|10:50:15.797] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.797] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
[TRACE] [08-21|10:50:15.797] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.804] [downloader] Link queue                  size=303460
[TRACE] [08-21|10:50:15.804] [downloader] Link queue                  size=303460
[TRACE] [08-21|10:50:15.804] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.805] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.810] [downloader] Link queue                  size=303645
[TRACE] [08-21|10:50:15.810] [downloader] Link queue                  size=303645
[TRACE] [08-21|10:50:15.810] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.810] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
[TRACE] [08-21|10:50:15.810] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.821] [downloader] Link queue                  size=303643
[TRACE] [08-21|10:50:15.821] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.821] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
[TRACE] [08-21|10:50:15.821] [downloader] Link queue                  size=303460
[TRACE] [08-21|10:50:15.821] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.824] [downloader] Link queue                  size=303460
[TRACE] [08-21|10:50:15.824] headerLoop woken up by the incoming request 
[TRACE] [08-21|10:50:15.837] >> FINDNODE/v4                           id=8ca5d13b0cbb45dbc683bcb727e800d10f59749c772f2343f0b887e623bf6b11 addr=94.130.27.127:30303 err=nil
[TRACE] [08-21|10:50:15.844] >> FINDNODE/v4                           id=8148eccb97f32f2f2fcdc73874b93ae4a3620431cc67b446f3ff405ce1243aef addr=86.30.186.245:30804 err=nil
[TRACE] [08-21|10:50:15.855] >> FINDNODE/v4                           id=814388910e5f835903342d97b2e6ae122c18126e413599e469394ff7070455fb addr=65.108.219.227:35415 err=nil
[TRACE] [08-21|10:50:15.875] << PING/v4                               id=af4d769236c3aba0e337bea631157419b406bf08bdd46edbababedea581b3d57 addr=74.201.193.135:31097 err=nil
[TRACE] [08-21|10:50:15.876] >> PONG/v4                               id=af4d769236c3aba0e337bea631157419b406bf08bdd46edbababedea581b3d57 addr=74.201.193.135:31097 err=nil
[TRACE] [08-21|10:50:15.920] << PING/v4                               id=1fdd4d10dc2f4e3fd349ad9cab839c399af98bafc7adab045a681577715ca9c7 addr=165.22.234.125:1651 err=nil
[TRACE] [08-21|10:50:15.921] >> PONG/v4                               id=1fdd4d10dc2f4e3fd349ad9cab839c399af98bafc7adab045a681577715ca9c7 addr=165.22.234.125:1651 err=nil
[TRACE] [08-21|10:50:15.921] [downloader] Link queue                  size=303641
[TRACE] [08-21|10:50:15.921] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.921] [downloader] Request skeleton            anchors=218 highestInDb=1920384
[DBUG] [08-21|10:50:15.922] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
[TRACE] [08-21|10:50:15.924] [downloader] Link queue                  size=303640
[TRACE] [08-21|10:50:15.924] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.924] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
[TRACE] [08-21|10:50:15.928] [downloader] Link queue                  size=303639
[TRACE] [08-21|10:50:15.928] headerLoop woken up by the incoming request 
[DBUG] [08-21|10:50:15.928] [downloader] Verification failed for header hash=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb height=1920000 err="bad DAO no-fork extra-data"
```           

https://blockscout.com/etc/mainnet/search-results?q=0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb

**Comment by meowsbits** [comment]
After the incident logged above, initially erigon seems to correctly reject block 1920000.

![screenshot_client_konsole_2023-08-22-073014](https://github.com/ETCCooperative/erigon/assets/45600330/b8276980-1c6c-4f57-a973-ffd938a60584)

But then somehow apparently a few hundred blocks above that height make it into the database.

![screenshot_client_konsole_2023-08-22-075231](https://github.com/ETCCooperative/erigon/assets/45600330/b4e3bccd-3ce2-4fe6-a766-bb920db17ecf)

Although I'm not sure that those extra blocks actually cause the stuck issue, since the `bad DAO no-fork extra data` error is continually logged. If not a downloader/verification/database issue, it could be a peering issue if the peer(s) supplying the bad fork are not dropped; I would expect this to happen and to see corresponding logs in geth, but I don't know erigon well enough to know whether this would present the same in erigon.

I reviewed the fork ID tests and they seem consistent with expectations and pass (DAO uncounted as fork).

**Comment by DRIgnazGortngschirl** [comment]
@meowsbits any update don't want to push but my nodes still down and what to keep them running to see if Erigon also is really supporting ETC. To provide such feedback if there are any bugs with the releases.

**Comment by meowsbits** [comment]
Hey @DRIgnazGortngschirl. Thanks for the bump, and many apologies for dropping this thread. I'll be back at it this week. I'm working right now on getting an upstream merge done (rabbit hole I feel into in first steps to reproducing this issue again this morn) -- and then with that we'll see if the issue is still there once :crossed_fingers: the develop+classic branch is working again.

**Comment by meowsbits** [comment]
Hello again @DRIgnazGortngschirl  -- the `devel+classic` branch is now fixed up and building, but with only a half resolution to the problem of actually getting ETC to sync. On my latest run erigon stalled out at 1920000 as earlier, but then with a restart it continued, and is now at 1937945 and climbing. Smells now more like a peering and chaindata availability issue rather than an ETC-validation issue, but no firm answers yet unfortunately.

**Comment by DRIgnazGortngschirl** [comment]
Hi @meowsbits thanks so much for looking into this. Both my nodes are currently syncing and one is in the 1.1 millions the other very slow (high I/O usage by other services therefor slow) at 220k I will update tomorrow when I passed 1.92 Mil mark.

**Comment by meowsbits** [comment]
Thanks for trying it out! And a heads up -- I just pushed again to `devel+classic`, maybe (if the hangup was at all related to the protocol bug in erigon) it'll get further than before... not sure, we'll see! 

I'm running this latest version now (https://github.com/ETCCooperative/erigon/commit/23c2885810bf2ad44409bf418873883fb72c513c) and am apparently inserting headers beyond 1.92M. Running on top of my old datadir (not a fresh sync).

```
Oct 25 11:53:57 ubp52 erigon[927435]: [INFO] [10-25|11:53:57.036] [2/15 Headers] No block headers to write in this log period number=1979630 blk/second=0.000 alloc=59.7MB sys=95.1MB invalidHeaders=0 rejectedBadHeaders=0
Oct 25 11:54:17 ubp52 erigon[927435]: [INFO] [10-25|11:54:17.036] [2/15 Headers] No block headers to write in this log period number=1979630 blk/second=0.000 alloc=72.6MB sys=95.2MB invalidHeaders=0 rejectedBadHeaders=0
Oct 25 11:54:17 ubp52 erigon[927435]: [INFO] [10-25|11:54:17.036] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=20 skelMin=1979629 skelMax=2016685 resp=1 respMin=0 respMax=0 dups=0
Oct 25 11:54:37 ubp52 erigon[927435]: [INFO] [10-25|11:54:37.036] [2/15 Headers] Inserting headers         progress=1983464 queue=1
Oct 25 11:54:57 ubp52 erigon[927435]: [INFO] [10-25|11:54:57.036] [2/15 Headers] Wrote block headers       number=1989472 blk/second=492.100 alloc=165.7MB sys=310.2MB invalidHeaders=0 rejectedBadHeaders=0
Oct 25 11:55:17 ubp52 erigon[927435]: [INFO] [10-25|11:55:17.037] [2/15 Headers] Inserting headers         progress=1995325 queue=1
Oct 25 11:55:35 ubp52 erigon[927435]: [INFO] [10-25|11:55:35.686] [p2p] GoodPeers                          eth68=4 eth67=2
Oct 25 11:55:37 ubp52 erigon[927435]: [INFO] [10-25|11:55:37.024] [txpool] stat                            pending=10 baseFee=0 queued=9 alloc=203.6MB sys=310.8MB
Oct 25 11:55:37 ubp52 erigon[927435]: [INFO] [10-25|11:55:37.038] [2/15 Headers] Inserting headers         progress=2000482 queue=1
Oct 25 11:55:57 ubp52 erigon[927435]: [INFO] [10-25|11:55:57.038] [2/15 Headers] Inserting headers         progress=2007507 queue=1
Oct 25 11:56:17 ubp52 erigon[927435]: [INFO] [10-25|11:56:17.036] [2/15 Headers] Inserting headers         progress=2012330 queue=1
Oct 25 11:56:37 ubp52 erigon[927435]: [INFO] [10-25|11:56:37.036] [2/15 Headers] Inserting headers         progress=2019004 queue=1
Oct 25 11:56:57 ubp52 erigon[927435]: [INFO] [10-25|11:56:57.039] [2/15 Headers] Inserting headers         progress=2025663 queue=1
```

**Comment by DRIgnazGortngschirl** [comment]
This is a freshly built Docker image + fresh sync. 

```
erigon_1                         | [INFO] [11-03|11:10:16.933] [2/15 Headers] Inserting headers         progress=1902924 queue=1
erigon_1                         | [INFO] [11-03|11:10:36.873] [p2p] GoodPeers                          eth68=24 eth67=19 eth66=3
erigon_1                         | [INFO] [11-03|11:10:36.922] [txpool] stat                            pending=0 baseFee=0 queued=18 alloc=304.2MB sys=695.5MB
erigon_1                         | [INFO] [11-03|11:10:36.932] [2/15 Headers] Inserting headers         progress=1906481 queue=1
erigon_1                         | [INFO] [11-03|11:10:56.933] [2/15 Headers] Inserting headers         progress=1910095 queue=1
erigon_1                         | [INFO] [11-03|11:11:16.934] [2/15 Headers] Inserting headers         progress=1913747 queue=1
erigon_1                         | [INFO] [11-03|11:11:36.934] [2/15 Headers] Inserting headers         progress=1917284 queue=1
erigon_1                         | [INFO] [11-03|11:11:56.932] [2/15 Headers] Wrote block headers       number=1920477 blk/second=50506.350 alloc=402.4MB sys=695.5MB invalidHeaders=6 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:12:16.933] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=351.5MB sys=695.5MB invalidHeaders=47 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:12:36.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=443.7MB sys=715.5MB invalidHeaders=38 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:12:56.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=418.6MB sys=732.0MB invalidHeaders=30 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:13:16.933] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=408.6MB sys=745.4MB invalidHeaders=26 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:13:36.872] [p2p] GoodPeers                          eth67=18 eth66=2 eth68=23
erigon_1                         | [INFO] [11-03|11:13:36.921] [txpool] stat                            pending=0 baseFee=0 queued=18 alloc=364.3MB sys=749.6MB
erigon_1                         | [INFO] [11-03|11:13:36.933] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=365.8MB sys=749.6MB invalidHeaders=33 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:13:56.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=388.2MB sys=757.6MB invalidHeaders=37 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:14:16.933] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=657.6MB sys=761.6MB invalidHeaders=32 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:14:36.933] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=534.2MB sys=778.1MB invalidHeaders=42 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:14:56.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=400.7MB sys=794.4MB invalidHeaders=55 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:15:16.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=377.0MB sys=794.4MB invalidHeaders=34 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:15:36.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=653.0MB sys=794.4MB invalidHeaders=44 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:15:56.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=572.9MB sys=794.4MB invalidHeaders=33 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:16:16.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=490.7MB sys=794.4MB invalidHeaders=34 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|11:16:36.873] [p2p] GoodPeers                          eth67=18 eth68=23 eth66=2
erigon_1                         | [INFO] [11-03|11:16:36.921] [txpool] stat                            pending=0 baseFee=0 queued=18 alloc=677.0MB sys=802.6MB
```

I tried to restart but all my progress is gone now and it starts all over.

```
erigon_1                         | [INFO] [11-03|11:17:52.873] [2/15 Headers] Inserting headers         progress=419 queue=1
erigon_1                         | [INFO] [11-03|11:18:12.878] [2/15 Headers] Inserting headers         progress=1551 queue=1
erigon_1                         | [INFO] [11-03|11:18:32.874] [2/15 Headers] Inserting headers         progress=5200 queue=1
erigon_1                         | [INFO] [11-03|11:18:52.875] [2/15 Headers] Inserting headers         progress=8880 queue=1
erigon_1                         | [INFO] [11-03|11:19:12.876] [2/15 Headers] Inserting headers         progress=12566 queue=1
erigon_1                         | [INFO] [11-03|11:19:32.873] [2/15 Headers] Inserting headers         progress=16275 queue=1
erigon_1                         | [INFO] [11-03|11:19:52.874] [2/15 Headers] Inserting headers         progress=19876 queue=1
erigon_1                         | [INFO] [11-03|11:20:12.873] [2/15 Headers] Inserting headers         progress=23563 queue=1
erigon_1                         | [INFO] [11-03|11:20:32.791] [p2p] GoodPeers                          eth68=4 eth67=3
erigon_1                         | [INFO] [11-03|11:20:32.862] [txpool] stat                            pending=9 baseFee=0 queued=9 alloc=126.0MB sys=259.5MB
```

Maybe some erors in my compose file on my side ? 
```
  erigon:
    volumes:
      - '/mnt/tank/erigon/:/home/erigon/.local/share/erigon/classic'
    image: erigon
    entrypoint: erigon --chain=classic  --http --txpool.api.addr=0.0.0.0:9090 --private.api.addr=0.0.0.0:9090 --http.addr=0.0.0.0 --http.api=eth,debug,net,web3,txpool,debug --rpc.batch.limit 1500 --http.vhosts=* --http.corsdomain=https://explorer-expedition.etc-network.info,https://chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info --datadir=/home/erigon/.local/share/erigon/classic
```

**Comment by meowsbits** [comment]
Dang!  

```
erigon_1                         | [INFO] [11-03|11:16:16.932] [2/15 Headers] No block headers to write in this log period number=1920477 blk/second=0.000 alloc=490.7MB sys=794.4MB invalidHeaders=34 rejectedBadHeaders=0
```

Well, the good news is it passed 1,920,000, which was the first concern. 

I would recommend letting it try to sync for more than 5 minutes if it seems to stall out -- maybe a couple hours or so. The client may be trying to come up with some new relevant peers after passing that bottleneck.  

> I tried to restart but all my progress is gone now and it starts all over.

Bummer. I don't know -- would need to have more logs and context to help diagnose that, but I don't see any errors in your Docker config.

**Comment by DRIgnazGortngschirl** [comment]
So left it running for some time, but it did not resolve. Also, I think that it went beyond 1,92Mil. because of the batches of blocks, it does or? 

```
erigon_1                         | [INFO] [11-03|14:15:32.874] [2/15 Headers] Inserting headers         progress=1911448 queue=1
erigon_1                         | [INFO] [11-03|14:15:52.875] [2/15 Headers] Inserting headers         progress=1914746 queue=1
erigon_1                         | [INFO] [11-03|14:16:12.878] [2/15 Headers] Inserting headers         progress=1918132 queue=1
erigon_1                         | [INFO] [11-03|14:16:32.872] [2/15 Headers] Wrote block headers       number=1920191 blk/second=81477.100 alloc=541.3MB sys=670.3MB invalidHeaders=37 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:16:52.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=606.3MB sys=789.7MB invalidHeaders=296 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:17:12.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=652.7MB sys=851.6MB invalidHeaders=218 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:17:32.793] [p2p] GoodPeers                          eth68=23 eth67=18 eth66=1
erigon_1                         | [INFO] [11-03|14:17:32.861] [txpool] stat                            pending=9 baseFee=0 queued=11 alloc=591.4MB sys=1.1GB
erigon_1                         | [INFO] [11-03|14:17:32.874] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=593.0MB sys=1.1GB invalidHeaders=262 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:17:52.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=734.9MB sys=1.2GB invalidHeaders=344 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:18:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=791.7MB sys=1.2GB invalidHeaders=265 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:18:32.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=857.4MB sys=1.4GB invalidHeaders=273 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:18:52.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=1.4GB sys=1.5GB invalidHeaders=369 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|14:19:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=1.1GB sys=1.7GB invalidHeaders=366 rejectedBadHeaders=0
...
erigon_1                         | [INFO] [11-03|19:05:32.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=3.2GB sys=3.8GB invalidHeaders=421 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|19:05:52.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.6GB sys=3.8GB invalidHeaders=449 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|19:06:12.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.0GB sys=3.8GB invalidHeaders=224 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|19:06:32.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.9GB sys=3.8GB invalidHeaders=374 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-03|19:06:52.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.3GB sys=3.8GB invalidHeaders=262 rejectedBadHeaders=0
...
erigon_1                         | [INFO] [11-04|09:18:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=1.9GB sys=3.9GB invalidHeaders=426 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:18:32.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=3.1GB sys=3.9GB invalidHeaders=407 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:18:52.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.7GB sys=3.9GB invalidHeaders=451 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:19:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.2GB sys=3.9GB invalidHeaders=358 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:19:32.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=3.3GB sys=3.9GB invalidHeaders=384 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:19:52.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.8GB sys=3.9GB invalidHeaders=432 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:20:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.2GB sys=3.9GB invalidHeaders=140 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:20:32.791] [p2p] GoodPeers                          eth66=1 eth68=33 eth67=31
erigon_1                         | [INFO] [11-04|09:20:32.861] [txpool] stat                            pending=9 baseFee=0 queued=12 alloc=3.4GB sys=3.9GB
erigon_1                         | [INFO] [11-04|09:20:32.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=3.4GB sys=3.9GB invalidHeaders=377 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:20:52.872] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.9GB sys=3.9GB invalidHeaders=474 rejectedBadHeaders=0
erigon_1                         | [INFO] [11-04|09:21:12.873] [2/15 Headers] No block headers to write in this log period number=1920191 blk/second=0.000 alloc=2.3GB sys=3.9GB invalidHeaders=421 rejectedBadHeaders=0
```

Another node I started to sync stuck on a different block.

```
etc-erigon-1  | [INFO] [11-04|09:20:29.160] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.1GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:20:49.158] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.2GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:21:09.146] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.3GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:21:29.137] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.4GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:21:49.128] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=1.8GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:22:09.126] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.0GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:22:29.127] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.1GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:22:49.019] [p2p] GoodPeers                          eth68=5 eth67=4
etc-erigon-1  | [INFO] [11-04|09:22:49.117] [txpool] stat                            pending=0 baseFee=0 queued=18 alloc=2.2GB sys=3.2GB
etc-erigon-1  | [INFO] [11-04|09:22:49.204] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.2GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:23:09.187] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.3GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
etc-erigon-1  | [INFO] [11-04|09:23:29.169] [2/15 Headers] No block headers to write in this log period number=1940448 blk/second=0.000 alloc=2.4GB sys=3.2GB invalidHeaders=0 rejectedBadHeaders=0
```
